In [2]:
import numpy as np
import tensorflow as tf
import random
a=tf.constant(10)
b=tf.constant(10)
print(a+b)

tf.Tensor(20, shape=(), dtype=int32)


In [3]:
x=np.random.rand(100).astype(np.float32)
x

array([0.22993803, 0.5818663 , 0.02524319, 0.47449082, 0.5179817 ,
       0.9895966 , 0.70389783, 0.26706403, 0.96558195, 0.5397399 ,
       0.3076651 , 0.607959  , 0.35809335, 0.32381487, 0.35727274,
       0.99316645, 0.73626566, 0.59987193, 0.59476906, 0.74771065,
       0.5798306 , 0.5229403 , 0.8351843 , 0.06415537, 0.01239133,
       0.09302871, 0.33657497, 0.5931069 , 0.14337279, 0.07222323,
       0.13833055, 0.62413174, 0.06229552, 0.49949744, 0.87516874,
       0.34460798, 0.8869259 , 0.80976164, 0.07498141, 0.25296545,
       0.97791404, 0.94623613, 0.5281431 , 0.00145266, 0.68915284,
       0.07966466, 0.12380925, 0.5297573 , 0.04588661, 0.6810573 ,
       0.89311653, 0.58685225, 0.12624893, 0.689652  , 0.05814064,
       0.26879793, 0.7082881 , 0.44352126, 0.21003899, 0.21608263,
       0.11286668, 0.9892653 , 0.36712435, 0.9314803 , 0.2775666 ,
       0.26655617, 0.8645162 , 0.06612408, 0.06562793, 0.5141531 ,
       0.7772861 , 0.12374119, 0.30699417, 0.11876076, 0.98078

In [4]:
y=x*0.2+0.2
W=tf.Variable(tf.random.normal([1]))
b=tf.Variable(tf.zeros([1]))

In [6]:
def mse_loss():
    ypred=W*x+b
    loss=tf.reduce_mean(tf.square(ypred-y))
    return loss

In [8]:
optimizer=tf.keras.optimizers.Adam()
for step in range(5000):
    optimizer.minimize(mse_loss,var_list=[W,b])
    if step % 500 == 0:
        print(step,W.numpy(),b.numpy())

0 [-0.66468537] [0.001]
500 [-0.29945853] [0.3365392]
1000 [-0.15082733] [0.37490144]
1500 [-0.05189548] [0.3300178]
2000 [0.03801152] [0.28360054]
2500 [0.11002216] [0.24641794]
3000 [0.15845369] [0.22142926]
3500 [0.18485387] [0.20781188]
4000 [0.19592722] [0.20210056]
4500 [0.19926165] [0.20038083]


In [10]:
import torch
import numpy as np

In [13]:
data = [
    [1,2],
    [3,4]
]
x_data = torch.tensor(data)
print(x_data)
print(type(x_data))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [14]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [17]:
x_ones=torch.ones_like(x_data)
print(x_ones)
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1259, 0.7973],
        [0.4486, 0.1511]])


In [21]:
shape=(2,2)
ones_ten=torch.ones(shape)
print(ones_ten)
zeros_ten=torch.zeros(shape)
print(zeros_ten)
rand_ten=torch.rand(shape)
print(rand_ten)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0827, 0.7912],
        [0.0837, 0.8156]])


In [23]:
tensor=torch.cat([ones_ten,zeros_ten])
print(tensor)

tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]])


In [24]:
ones_ten.mul(zeros_ten)
ones_ten * zeros_ten
ones_ten.T

tensor([[1., 1.],
        [1., 1.]])

In [25]:
ones_ten.add_(3)
print(ones_ten)

tensor([[4., 4.],
        [4., 4.]])


In [26]:
n=tensor.numpy()
print(n)
print(type(n))

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [43]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [44]:
df=pd.read_csv(r"C:\Users\yasha\Desktop\Ashish\sem 7\DL\Datasets\diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [45]:
x=df.iloc[:,0:8]
print(x.shape)
y=df.iloc[:,8]
print(y)

(768, 8)
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [46]:
model=Sequential()
model.add(Dense(12,input_shape=(8,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [47]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [48]:
model.fit(x,y,epochs=100,batch_size=10)

Epoch 1/100
77/77 [==============================] - 1s 4ms/step - loss: 0.7761 - accuracy: 0.6341
Epoch 2/100
77/77 [==============================] - 0s 2ms/step - loss: 0.7207 - accuracy: 0.6471
Epoch 3/100
77/77 [==============================] - 0s 3ms/step - loss: 0.7058 - accuracy: 0.6445
Epoch 4/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6970 - accuracy: 0.6471
Epoch 5/100
77/77 [==============================] - 0s 4ms/step - loss: 0.6662 - accuracy: 0.6510
Epoch 6/100
77/77 [==============================] - 0s 4ms/step - loss: 0.6581 - accuracy: 0.6562
Epoch 7/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6547 - accuracy: 0.6549
Epoch 8/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6526 - accuracy: 0.6549
Epoch 9/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6502 - accuracy: 0.6549
Epoch 10/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6486 - accuracy: 0.6562
Epoch 11/

In [49]:
model.evaluate(x,y)

24/24 [==============================] - 0s 3ms/step - loss: 0.6437 - accuracy: 0.6536


[0.6436755061149597, 0.6536458134651184]